# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Seed data for car_makes table.
CarMake.create(name: 'Acura')
CarMake.create(name: 'Alfa Romeo')
CarMake.create(name: 'Aston Martin')
CarMake.create(name: 'Bentley')
CarMake.create(name: 'BMW')
CarMake.create(name: 'Buick')
CarMake.create(name: 'Cadillac')
CarMake.create(name: 'Chevrolet')
CarMake.create(name: 'Chrysler')
CarMake.create(name: 'Dodge')
CarMake.create(name: 'Ferrari')
CarMake.create(name: 'FIAT')
CarMake.create(name: 'Ford')
CarMake.create(name: 'Genesis')
CarMake.create(name: 'Geo')
CarMake.create(name: 'GMC')
CarMake.create(name: 'Honda')
CarMake.create(name: 'Hummer')
CarMake.create(name: 'Hyundai')
CarMake.create(name: 'Infiniti')
CarMake.create(name: 'Isuzu')
CarMake.create(name: 'Jaguar')
CarMake.create(name: 'Jeep')
CarMake.create(name: 'Kia')
CarMake.create(name: 'Lamborghini')
CarMake.create(name: 'Land Rover')
CarMake.create(name: 'Lincoln')
CarMake.create(name: 'Lotus')
CarMake.create(name: 'Maserati')
CarMake.create(name: 'Mazda')
CarMake.create(name: 'McLaren')
CarMake.create(name: 'Mercedes-Benz')
CarMake.create(name: 'Mercury')
CarMake.create(name: 'MINI')
CarMake.create(name: 'Mitsubishi')
CarMake.create(name: 'Nissan')
CarMake.create(name: 'Oldsmobile')
CarMake.create(name: 'Plymouth')
CarMake.create(name: 'Pontiac')
CarMake.create(name: 'Porsche')
CarMake.create(name: 'Ram')
CarMake.create(name: 'Rolls-Royce')
CarMake.create(name: 'Saab')
CarMake.create(name: 'Saturn')
CarMake.create(name: 'Scion')
CarMake.create(name: 'Smart')
CarMake.create(name: 'Subaru')
CarMake.create(name: 'Suzuki')
CarMake.create(name: 'Tesla')
CarMake.create(name: 'Toyota')
CarMake.create(name: 'Volkswagen')
CarMake.create(name: 'Volvo')


